language: python
services: mongodb
python:
- 3.3
- 3.4
install:
- python -c "import asyncio"; if [ $? -eq 1 ]; then
  pip install asyncio;
  fi
- pip install -r test-requirements.txt
- pip install pytest-cov coveralls
script:
- py.test -v --cov harpseal --cov-report term-missing
after_success:
- coveralls --rcfile=.coveragerc
notifications:
  email: false
  irc: 
    channels:
    - "irc.ozinger.org#ssut"
    on_success: change
    on_failure: always
