language: python
services: mongodb
python:
- 3.3
- 3.4
matrix:
  include:
  - python: 3.3
    env: PYTHON_ASYNCIO=0
  - python: 3.4
    env: PYTHON_ASYNCIO=1
install:
- if [[ $PYTHON_ASYNCIO -eq 0 ]]; then
    pip install asyncio;
  fi
- pip install -r test-requirements.txt
- pip install pytest-cov coveralls
script:
- coverage run --source harpseal -m py.test --durations=20
after_success:
- coverage report
- coveralls --rcfile=.coveragerc
notifications:
  email: false
  irc: 
    channels:
    - "irc.ozinger.org#ssut"
    on_success: change
    on_failure: always
